### ISSUE TITLE
Angular Cli template parse Error on *ngFor

### ISSUE THREAD

**Issue by longhatdev** [danguilherme/ng-cli-pug-loader#18]
Hi there,

if i use this code
`.grid.grid-pad
  a.col-1-4(*ngfor='let hero of heroes')
    .module.hero
      h4 {{ hero.name }}`

it compiles succesfully, but when i open the browser i get a template parse error
![image](https://user-images.githubusercontent.com/29131220/52156683-03a50700-268a-11e9-8450-a55c9d07f50d.png)

i found no solution to this issue

thank you

**Comment by danguilherme** [comment]
I am really not sure, but does it work if you use `ngFor` (note the capital `F`)?

**Comment by longhat-plenty** [comment]
Hi,

thank you, that helped in the first attempt... did not saw that... should not use that lazy html-to-pug converter in my IDE

so that was not a real issue of your pug-loader, shame on me ;)

beste regards
longhat

**Comment by longhatdev** [comment]
Hi,

thank you, that helped in the first attempt... did not saw that... should not use that lazy html-to-pug converter in my IDE

so that was not a real issue of your pug-loader, shame on me ;)

beste regards
longhat

**Comment by danguilherme** [comment]
All good! 😁
