### ISSUE TITLE
Angular 7

### ISSUE THREAD

**Issue by perrosen** [danguilherme/ng-cli-pug-loader#19]
Trying to update to Angular 7 and now seem to have an issue with pug files. On load the templates return 404 errors.

Assuming this would be an issue with CLI changes and the updates cli pug loader does to the webpack config during post install. 

Anyone tried a Angular 7 update yet and have any pointers?

**Comment by danguilherme** [comment]
I have not tested it in Angular 7.
If someone else could report this I'd be more than happy!

**Comment by adayrit** [comment]
> Trying to update to Angular 7 and now seem to have an issue with pug files. On load the templates return 404 errors.
> 
> Assuming this would be an issue with CLI changes and the updates cli pug loader does to the webpack config during post install.
> 
> Anyone tried a Angular 7 update yet and have any pointers?

experiencing the same thing.

**Comment by perrosen** [comment]
@danguilherme yeah would be super awesome. Happy to help if needed. Currently starting to come into some dependency issues and an upgrade to 7 would be really helpful :)

**Comment by m-przybylski** [comment]
I tried to use library with my Angular 7 application. It works wine with JiT, but does not work with AoT.

**Comment by danguilherme** [comment]
I would be very happy to accept a PR!
Apparently not even Angular 8 is supported by this version. Will have to check, can't compromise with time now.

@m-przybylski:
> However when I put it into newly created project it works just fine.

Could you elaborate on that?
You migrated your application from Angular 6 to 7, and the app does not work on AoT mode, but if you add the package on a newly created app (with v7), it works in both AoT and JiT?

**Comment by raykin** [comment]
I have a different problem on Angular7 with ionic4 and fixed in a workaround.
I've install pug-loader when the `ionic serve`(actually wrap ng serve) started and it success, but restart the `ionic serve` the pug file can not recognized any more.
I think the reproduce steps are: 
The init state is 1. Install ionic globally and launch a new ionic project server. 2. `which ng` return not found.
Then I have to install angular-cli globally to have `ng` command to install the pug loader. At current state, I can use pug in previous launched server.
Then I restart the ionic server and it alerts pug file is not recognized.

I finally realize the pug loader add rules to local lib. Without angular-cli installed globally, ionic will run ng from local, but if the angular-cli installed, ionic will call ng from global. And `ng serve` from global doesn't have the rule inserted. 
So in my case I uninstall angular-cli from global and the `ionic serve` works with pug template again.

Hope this case can help others too.

**Comment by danguilherme** [comment]
Great finding @raykin, thanks for sharing!

If I'm not mistaken, Angular CLI shows a warning when we're using a global installed `ng` instead of a local one - which means that the solution you described is the recommended way.

Maybe Ionic server just swallows that warning.

**Comment by JoshuaNitschke** [comment]
FYI, I was on Angular 7 without any issues.

**Comment by gabynevada** [comment]
Angular 8 is not working properly even after new update.
It gives this error on the console
```
Uncaught Error: Template parse errors:
'module' is not a known element:
1. If 'module' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
```

Any ideas on how to fix it?

**Comment by JoshuaNitschke** [comment]
Try running npm install

**Comment by gabynevada** [comment]
I tried npm install, it runs the post install script but the same error pops up after I run ng serve.

I also tried to npm uninstall the module as it doesn't update the ng-add-pug-loader.js script when you install the latest version, even after making sure I had the latest version installed, the correct script and doing npm install I still get the same error.

**Comment by JoshuaNitschke** [comment]
Is your index file html or pug?

Mine is html, everything else is pug.  I'm not sure if that makes a
difference.  Everything is running fine on my current angular 8 project
now.

If I have time I'll try to make a new project from scratch and see if I can
reproduce your issue.

**Comment by gabynevada** [comment]
Yes, the index is html and everything else is pug.

Thanks, i'll test it on a new angular project as well, see if I get the
same issue.

**Comment by JoshuaNitschke** [comment]
Did you see this?  What version of node are you using?
https://github.com/pugjs/pug-loader/issues/120

node -v
v10.7.0

**Comment by usman-vqode** [comment]
Using nod 10.16 here and still getting the same error on Angular 8. Any solutions found for this?

**Comment by gabynevada** [comment]
I got node 10.16.

+ If I create a new Angular 8 project, it works fine.
+ If I upgrade just the ng-cli-pug-loader on my angular 7 project it stops working and gives back the prior 'module' is not a known element error.
+ If I upgrade existing project to Angular 8 and upgrade ng-cli-pug-loader it errors out as well.

**Comment by SlateDave** [comment]
> npm clean-install
 worked for me and fixed the issue.

**Comment by gabynevada** [comment]
For me deleting the package for the commonCli config and then doing an npm install worked.

Apparently the old pug loader script changes were messing with the new one and it wasn't working correctly.

**Comment by perrosen** [comment]
@gabynevada What was the package you deleted? Currently running into the "'module' is not a known element:" on an Angular 8 project that has been updated from 7.

**Comment by perrosen** [comment]
@gabynevada Never mind. A clean npm i sorted it for me.

**Comment by danguilherme** [comment]
This project is no longer maintained. Check out [ngx-pug-builders](https://github.com/lekhmanrus/ngx-pug-builders) to add support to pug files to the latest versions of Angular.
