### ISSUE TITLE
Angular 8

### ISSUE THREAD

**Issue by Marcoswinrar** [danguilherme/ng-cli-pug-loader#20]
Fiz alguns testes com o Angular 8 e aparentemente o pug não está sendo identificado no mesmo. Teremos suporte para está versão ?

**Comment by danguilherme** [comment]
Ainda não, nem pra versão 7, como visto aqui: #19.

Ficaria muito feliz em receber um PR!

**Comment by Marcoswinrar** [comment]
Opa @danguilherme , nós temos um app que usamos desde o 6 e que por sinal está no 7 funcionando perfeitamente pós migração. O quesito é que eu andei apenas testando no 8-beta criando uma nova app e ele não consegue identificar.

**Comment by MateEke** [comment]
I think this commint breaks the functionality of the package https://github.com/angular/angular-cli/commit/dfb08b95b73f3e75d0f2cd0c61f336dc86d0769a in Angular 8

**Comment by JoshuaNitschke** [comment]
Here's an update ng-add-pug-loader.js script that fixes the issue.

[ng-add-pug-loader.js.zip](https://github.com/danguilherme/ng-cli-pug-loader/files/3278831/ng-add-pug-loader.js.zip)

I tried to update the code here, but i see it's failing unit tests, and I don't have time to mess around with that.  Hopefully this helps.

**Comment by danguilherme** [comment]
Solved in PR #22. Thanks @JoshuaNitschke!

**Comment by rHilkner** [comment]
Galera, fiz update pra Angular 8.2.0, deletei os node_modules, rodei npm install de novo, npm clean-install também, nada funciona... ideia de como consertar isso? To quase passando a transcrever o pug por conta própria e desistindo de usar o package...
