### ISSUE TITLE
Better future-proofing?

### ISSUE THREAD

**Issue by selipso** [danguilherme/ng-cli-pug-loader#3]
It seems like the angular team is changing the inner workings of the common.js webpack file. Is there a possible way to add the loaders as part of the angular.json file? Relevant issue for reference:

https://github.com/angular/angular-cli/issues/10879

**Comment by danguilherme** [comment]
I'm afraid I can't do anything about it :(

The only thing I can do is to wait for the next releases of the CLI, and if the script is broken in any of these releases, fix the scripts when it happens (PRs are always welcome).  What I could do was to [separate the file path](https://github.com/danguilherme/ng-cli-pug-loader/blob/master/src/schematics/ng-add/index.ts#L14) to easily change if any release moves it.
 
We need to remember that there's not an "official way" to add loaders to Angular CLI's webpack config, so this is a tricky workaround.

**Comment by selipso** [comment]
The future is definitely hard to predict. On the other hand there will always be some node_modules folder that can be edited to use a custom loader. Going to close as answered.
