### ISSUE TITLE
v0.2.2 has wrong NPM dependencies

### ISSUE THREAD

**Issue by matheo** [danguilherme/ng-cli-pug-loader#30]
Instead
```
"dependencies": {
  "@angular-devkit/core": "^0.5.13",
  "@angular-devkit/schematics": "^0.5.13"
},
```
you should define something like
```
"peerDependencies": {
  "@angular-devkit/core": ">=0.5.13 < 0.900.0",
  "@angular-devkit/schematics": ">=0.5.13 < 0.900.0"
},
```
because your script is supposed to modify the files of those packages, already installed, and defining them as dependencies, you're adding `@angular-devkit/core@0.5.13` to our angular projects, instead just work with the existing files.

Thanks for the great work.

**Comment by danguilherme** [comment]
Hey, thanks for pointing it out! Will check this asap.

**Comment by matheo** [comment]
and if you release `0.2.3`, it will fix the projects including `~0.2.2` or `^0.2.0` ;)

**Comment by matheo** [comment]
@danguilherme now that I think about it
you could simplify the current requirements given that the webpack loaders haven't new recent versions, you could define apply-loader and pug-loader as dependencies, maybe it's convenient to define pug as peerDependency, but it can be a required dependency too.
I may build a PR soon ;)

**Comment by matheo** [comment]
Closed because this library got unmaintained
