### ISSUE TITLE
[Feature Request] Support Integration of pug-plugin-ng

### ISSUE THREAD

**Issue by ScallyGames** [danguilherme/ng-cli-pug-loader#32]
Finally this is a proper solution to use pug with angular-cli.

However it would be nice to have support for quote-less usage of angular binding syntax (`[]`, `()`, `[()]`) as provided by https://github.com/tycho01/pug-plugin-ng.

Is there any way to register the plugin to the loader?

**Comment by danguilherme** [comment]
This project is no longer maintained. Check out [ngx-pug-builders](https://github.com/lekhmanrus/ngx-pug-builders) to add support to pug files to your Angular project.
