### ISSUE TITLE
Pug support inside angular libraries

### ISSUE THREAD

**Issue by donmahallem** [danguilherme/ng-cli-pug-loader#33]
Currently I am facing issues with using pug in angular libraries.

The ng-packgr does naivly assume that everything BUT html,htm and svg files are css files

https://github.com/ng-packagr/ng-packagr/blob/6234bafb31559cf5825d37db8d729ef3502a4ef9/src/lib/ts/cache-compiler-host.ts#L131

This results in the css processor choking on pug files and throwing errors. Adding a pug to that line fixes the issue but I am not sure if this library is the right scope for that issue.

**Comment by donmahallem** [comment]
Someone else already did some work on this:

https://github.com/crexi-dev/ng-packagr/pull/1/files

**Comment by valera33** [comment]
any news ?

**Comment by danguilherme** [comment]
This project is no longer maintained. Check out [ngx-pug-builders](https://github.com/lekhmanrus/ngx-pug-builders) to add support to pug files to your Angular project.
