### ISSUE TITLE
Build errors when using AOT compiler

### ISSUE THREAD

**Issue by selipso** [danguilherme/ng-cli-pug-loader#4]
I'm getting the following error when I try to build the package (the aot compiler actually swallows this error and starts at the router-outlet).

```
ERROR in ./src/app/shared/Philosopher/choices/choices.component.pug
Module parse failed: Unexpected token (3:4)
You may need an appropriate loader to handle this file type.
| ol(type="A")
|   li(
|     *ngFor="let choice of choices",
|     [ngClass]="{correct: displayCorrect && choice.correct}"
|     ) 
```

**Comment by selipso** [comment]
I was able to resolve these by explicitly telling the docker container to run `npm run postinstall` inside the directory.

**Comment by danguilherme** [comment]
This should be run automatically after an `npm install` 🤔

**Comment by TLmaK0** [comment]
Running npm install as root doesn't run postinstall

**Comment by danguilherme** [comment]
Thanks for the tip @TLmaK0, that really seems to be the problem: https://stackoverflow.com/a/19132229/1574059.

Not sure how to automatically fix this. Maybe just adding a note in the README would be enough...

**Comment by TLmaK0** [comment]
Yes, I think adding the error and the solution in the README, should be enough. Google will do the rest :)
